//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mojj_novyjj_proekt_20191206
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Микрофон.
    /// </summary>
    //  *** Start programmer edit section *** (Микрофон CustomAttributes)

    //  *** End programmer edit section *** (Микрофон CustomAttributes)
    [PublishName("Mic")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МикрофонE", new string[] {
            "Название as \'Название\'"})]
    [View("МикрофонL", new string[] {
            "Название as \'Название\'"})]
    public class Микрофон : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        //  *** Start programmer edit section *** (Микрофон CustomMembers)

        //  *** End programmer edit section *** (Микрофон CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Микрофон.Название CustomAttributes)

        //  *** End programmer edit section *** (Микрофон.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Микрофон.Название Get start)

                //  *** End programmer edit section *** (Микрофон.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Микрофон.Название Get end)

                //  *** End programmer edit section *** (Микрофон.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Микрофон.Название Set start)

                //  *** End programmer edit section *** (Микрофон.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Микрофон.Название Set end)

                //  *** End programmer edit section *** (Микрофон.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МикрофонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МикрофонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МикрофонE", typeof(IIS.Mojj_novyjj_proekt_20191206.Микрофон));
                }
            }
            
            /// <summary>
            /// "МикрофонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МикрофонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МикрофонL", typeof(IIS.Mojj_novyjj_proekt_20191206.Микрофон));
                }
            }
        }
    }
}
