//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mojj_novyjj_proekt_20191206
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Работник сцены.
    /// </summary>
    //  *** Start programmer edit section *** (РаботникСцены CustomAttributes)

    //  *** End programmer edit section *** (РаботникСцены CustomAttributes)
    [AutoAltered()]
    [Caption("Работник сцены")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РаботникСценыE", new string[] {
            "ФИО as \'ФИО\'"})]
    [View("РаботникСценыL", new string[] {
            "ФИО as \'ФИО\'"})]
    public class РаботникСцены : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        //  *** Start programmer edit section *** (РаботникСцены CustomMembers)

        //  *** End programmer edit section *** (РаботникСцены CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (РаботникСцены.ФИО CustomAttributes)

        //  *** End programmer edit section *** (РаботникСцены.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (РаботникСцены.ФИО Get start)

                //  *** End programmer edit section *** (РаботникСцены.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (РаботникСцены.ФИО Get end)

                //  *** End programmer edit section *** (РаботникСцены.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РаботникСцены.ФИО Set start)

                //  *** End programmer edit section *** (РаботникСцены.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (РаботникСцены.ФИО Set end)

                //  *** End programmer edit section *** (РаботникСцены.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РаботникСценыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаботникСценыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаботникСценыE", typeof(IIS.Mojj_novyjj_proekt_20191206.РаботникСцены));
                }
            }
            
            /// <summary>
            /// "РаботникСценыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаботникСценыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаботникСценыL", typeof(IIS.Mojj_novyjj_proekt_20191206.РаботникСцены));
                }
            }
        }
    }
}
